name: Run Scraper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Push committed changes
        run: |
          git config --global user.email "runningcalligraphy@gmail.com"
          git config --global user.name "Running Wong"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/runningnose852/scape.git
          git add README.md
          git commit -m "Add test line"
          git push

