name: Run Scraper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Runningggg (EXAMPLE)
        run: |
          echo "Test line" >> README.md
          git config --global user.email "runningcalligraphy@gmail.com"
          git config --global user.name "Running Wong"
          git add README.md
          git commit -m "Add test line"
          git push
